Move over fixes from other tree.

diff --git a/cmds/vmware/content/templates/esxi-set-insecure-password.sh.tmpl b/cmds/vmware/content/templates/esxi-set-insecure-password.sh.tmpl
--- a/cmds/vmware/content/templates/esxi-set-insecure-password.sh.tmpl
+++ b/cmds/vmware/content/templates/esxi-set-insecure-password.sh.tmpl
@@ -42,14 +42,25 @@ echo "No insecure password ('esxi/insecure-password' and 'esxi/insecure-password
 exit 0
 {{ end -}}
 
+[[ -n "$RS_DEBUG_ENABLE" ]] && echo "DEBUG:  'PASS' value to be set to '$PASS'."
+
 {{ if .ParamExists "esxi/insecure-password" -}}
 drpcli machines remove {{.Machine.UUID}} param "esxi/insecure-password"
 {{ end -}}
-drpcli machines add {{.Machine.UUID}} param "esxi/insecure-password" to "$PASS"
-CRYPT=$(python -c "import crypt; print crypt.crypt('$PASS', crypt.mksalt(crypt.METHOD_SHA512))")
-echo "Recording password hash on DRP Endpoint for Machine {{.Machine.UUID}}"
-echo "Some day we might send this to some other external system ... "
-{{ if .ParamExists "provisioner-default-password-hash" -}}
-drpcli machines remove {{.Machine.UUID}} param "provisioner-default-password-hash"
-{{ end -}}
-drpcli machines add {{.Machine.UUID}} param "provisioner-default-password-hash" to "$CRYPT"
+
+if [[ -n "$PASS" ]]; then
+  drpcli machines add {{.Machine.UUID}} param "esxi/insecure-password" to "$PASS"
+  CRYPT=$(python -c "import crypt; print crypt.crypt('$PASS', crypt.mksalt(crypt.METHOD_SHA512))")
+  echo "Recording password hash on DRP Endpoint for Machine {{.Machine.UUID}}"
+  echo "Some day we might send this to some other external system ... "
+  {{ if .ParamExists "provisioner-default-password-hash" -}}
+  drpcli machines remove {{.Machine.UUID}} param "provisioner-default-password-hash"
+  {{ end -}}
+  drpcli machines add {{.Machine.UUID}} param "provisioner-default-password-hash" to "$CRYPT"
+else
+  echo "FATAL: 'PASS' value in 'esxi-set-insecure-password.sh.tmpl' template was empty."
+  echo "       Somehow the 'passgen.py.tmpl' failed to produce a password string, the"
+  echo "       or either 'esxi/insecure-password-override' or 'esxi/insecure-password' were"
+  echo "       added to the machine with an empty value."
+  exit 1
+fi
