enhance(vmware): Add kickstart/firstboot handling

diff --git a/cmds/vmware/content/templates/esxi-set-network.sh.tmpl b/cmds/vmware/content/templates/esxi-set-network.sh.tmpl
--- a/cmds/vmware/content/templates/esxi-set-network.sh.tmpl
+++ b/cmds/vmware/content/templates/esxi-set-network.sh.tmpl
@@ -1,6 +1,8 @@
 #!/usr/bin/env sh
 # set firstboot network configuration settings
 
+function xiterr() { [[ $1 =~ ^[0-9]+$ ]] && { XIT=$1; shift; } || XIT=1; printf "FATAL: $*\n"; exit $XIT; }
+
 {{ if eq (.Param "rs-debug-enable") true }}set -x{{ end }}
 
 VMK="{{ .Param "esxi/network-firstboot-vmk" }}"
@@ -10,6 +12,7 @@ VMK="{{ .Param "esxi/network-firstboot-vmk" }}"
 ###
 {{ if .ParamExists "esxi/network-firstboot-vlan" -}}
 VLAN_MGMT={{ .Param "esxi/network-firstboot-vlan" }}
+SET_VLAN="--vlan=$VLAN_MGMT"
 SET_VLAN_MGMT="esxcli network vswitch standard portgroup set --portgroup-name=\"Management Network\" --vlan-id=$VLAN_MGMT"
 {{ end -}}
 {{ if .ParamExists "esxi/network-firstboot-vlan-vm-network" -}}
@@ -26,7 +29,7 @@ then
     else
       echo "FATAL: Requested 'VM Network' portgroup be set to value of 'Management"
       echo "       Network' VLAN - but Management VLAN did not validate to 0-4096"
-      echo "       ** We should never have gotten here ... :( **"
+      echo "       ** We should never have gotten here ... **"
       exit 1
     fi
   fi
@@ -54,17 +57,104 @@ SET_MTU_VMK="esxcli network ip interface set --mtu={{ .Param "esxi/network-first
 [[ -n "$SET_MTU_VSW"   ]] && eval ${SET_MTU_VSW}
 [[ -n "$SET_MTU_VMK"   ]] && eval ${SET_MTU_VMK}
 
-{{ if eq (.Param "esxi/network-firstboot-type") "manual" }}
+{{ if .ParamExists "esxi/network-firstboot-vmnic" -}}
+if [[ $(esxcfg-vswitch --check vSwitch0) == "1" ]]
+then
+  echo "vSwitch0 exists, continuing"
+else
+  echo "FATAL: 'vSwitch0' does not appear to exist, how did this happen?"
+  exit 1
+fi
+
+{{ if .ParamExists "esxi/network-kickstart-vmnic" -}}
+PNIC_INST='{{ .Param "esxi/network-kickstart-vmnic" }}'
+{{ else -}}
+PNIC_INST='{{ .Param "esxi/vmnic-device" }}'
+{{ end -}}
+PNIC_REQ='{{ .Param "esxi/network-firstboot-vmnic" }}'
+PNIC_CUR="$(esxcfg-vswitch --list vSwitch0 | grep "Management Network" | awk ' { print $NF } ' )"
+PNICS=$(esxcfg-nics --list | grep -v "^Name" | awk ' { print $1 } ' | sed 's/$/,/g')
+
+if echo $PNICS | grep -q "$PNIC_REQ"
+then
+  echo ">>> '$PNIC_REQ' exists on system, attempting link operations"
+else
+  xiterr 1 "Requested NIC '$PNIC_REQ' not available on system. Found: $PNICS"
+fi
+
+pnic_in_vswitch() {
+  _pnic="$1"
+
+  if esxcfg-vswitch --list vSwitch0 | grep "Management Network" | awk ' { print $NF } ' | sed 's/$/,/' | grep -q "${_pnic},"
+  then
+    return 0
+  else
+    return 1
+  fi
+}
+
+skip_pnic_op() {
+  echo "$*"
+  SKIP_PNIC_OP=yes
+}
+
+[[ "$PNIC_INST" == "$PNIC_REQ" ]] && skip_pnic_op "Requested ($PNIC_REQ) and installed physical NIC ($PNIC_INST) same." || true
+echo "$PNIC_CUR" | grep -q "$PNIC_REQ" && skip_pnic_op "Requested physical NIC ($PNIC_REQ) already linked in vSwitch0." || true
+
+if [[ "$SKIP_PNIC_OP" != "yes" ]]
+then
+  echo ">>> Linking '$PNIC_REQ' into vSwitch0"
+
+  if pnic_in_vswitch "${PNIC_REQ}"
+  then
+    echo "Requested physical NIC ('$PNIC_REQ') exists in Virtual Switch vSwitch0 already."
+  else
+    echo "+++ Linking in '$PNIC_REQ' to vSwitch0"
+    esxcfg-vswitch --link=$PNIC_REQ $SET_VLAN vSwitch0
+  fi
+
+  if pnic_in_vswitch "${PNIC_REQ}"
+  then
+    echo "+++ Physical NIC '$PNIC_REQ' linked in to vSwitch0 successfully"
+  else
+    xiterr 1 "Failed to link '$PNIC_REQ' in to vSwitch0"
+  fi
+
+  echo ">>> Starting unlink operation of '$PNIC_INST'"
+
+  if pnic_in_vswitch "${PNIC_INST}"
+  then
+    echo ">>> Unlinking kickstart '${PNIC_INST}' from vSwitch0"
+    esxcfg-vswitch --unlink=${PNIC_INST} vSwitch0
+  else
+    echo "--- '${PNIC_INST}' not found in vSwitch0, no unlink operation performed"
+  fi
+
+  if [[ "$PNIC_CUR" != "$PNIC_INST" ]]
+  then
+    if pnic_in_vswitch "${PNIC_CUR}"
+    then
+      echo ">>> Unlinking current '${PNIC_CUR}' from vSwitch0"
+      esxcfg-vswitch --unlink=${PNIC_CUR} vSwitch0
+    fi
+  fi
+fi
+
+{{- end }}
+
+{{ if eq (.Param "esxi/network-firstboot-type") "manual" -}}
 
 IP="{{ .Param "esxi/network-firstboot-ipaddr" }}"
 NM="{{ .Param "esxi/network-firstboot-netmask" }}"
 GW="{{ .Param "esxi/network-firstboot-gateway" }}"
+
 for CHECK in "ipaddr:$IP" "netmask:$NM" "gateway:$GW" "vmkernel_interface:$VMK"
 do
   T=$(echo $CHECK | cut -d":" -f1)
-  V=$(echo $CHECK | cut -d":" -f1)
+  V=$(echo $CHECK | cut -d":" -f2)
   [[ -z "$V" ]] && (echo "FATAL: Required value ('$T') missing for 'manual' network config."; exit 1)
 done
+
 esxcli network ip interface ipv4 set --type=static --interface-name="${VMK}" --ipv4="${IP}" --netmask="${NM}" --gateway="${GW}"
 esxcfg-route ${GW}
 esxcli system syslog reload
